#!/bin/bash
#SBATCH -q serial
#SBATCH -e /scratch/afdossan/job-%N-%j.err
#SBATCH -o /scratch/afdossan/job-%N-%j.out
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --time 04:00:00
#SBATCH --mem 6G
#SBATCH --output=logs/%A_%a.out
#SBATCH --error=logs/%A_%a.err
#SBATCH --array=1-201


export SCR=/scratch/afdossan
export DAT=/home/afdossan/Samuel_SSL_IPEPS
export RES=/home/afdossan/Samuel_SSL_IPEPS/Results

echo "***** START OF JOB ***** "

cd $SCR
mkdir $SLURM_JOB_ID
cd ./$SLURM_JOB_ID

cp -a $DAT/. .

module purge
module load gcc julia

echo STARTING AT `date`

D=${D:-2}
multiD=${multiD:-0}


hmin=${hmin:-0.0}
hmax=${hmax:-3.0}

hx=${hx:-0.00}
Delta=${Delta:-0.25}
J1=${J1:-3.2}
J2=${J2:--10.6}
N=${N:-6}
Jx=${Jx:-0.25}
Jy=${Jy:-0.50}
Jz=${Jz:-1.00}
Delta1=${Delta1:-1.0}
Delta2=${Delta2:-0.5}
eta=${eta:-0.0}
H_dir=${H_dir:-100}
model=${model:-Tb_SSL}

hz=$(echo "scale=3;$hmin + ($hmax-$hmin)*($SLURM_ARRAY_TASK_ID-1)/($SLURM_ARRAY_TASK_COUNT-1)" | bc -l)
echo "D=$D"
echo "multiD=$multiD"

for curD in $(seq $D 1 $(echo "$D+$multiD"|bc)); do
    echo "Running with parameters:"
    echo "D=$curD J1=$J1 J2=$J2 Delta=$Delta hx=$hx hz=$hz N=$N"
    echo "Jx=$Jx Jy=$Jy Jz=$Jz Delta1=$Delta1 Delta2=$Delta2 eta=$eta H_dir=$H_dir model=$model"
    julia --project=. -t 1 main.jl "$curD" "$J1" "$J2" "$Delta" "$hx" "$hz" "$N" "$Jx" "$Jy" "$Jz" "$Delta1" "$Delta2" "$eta" "$H_dir" "$model"
    mkdir -p $RES
    cp $SCR/$SLURM_JOB_ID/Results/* $RES
done

echo FINISHED at `date`

echo " ***** END OF JOB ***** "

